language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
env:
    - TESTING=True
    - TEST_DATABASE_URL=postgres://localhost:5432/stocks_test
services:
  - postgresql
before_script:
  - psql -c 'create database stocks_test;' -U postgres
